name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for User service
        run: npm install --prefix ./user-service

      - name: Install dependencies for Product service
        run: npm install --prefix ./product-service

      #- name: Run tests for User service
       # run: npm test --prefix ./user-service

      #- name: Run tests for Product service
       # run: npm test --prefix ./product-service

      - name: Build Docker images
        run: |
          docker build -t praveshparashar77081/user-service ./user-service
          docker build -t praveshparashar77081/product-service ./product-service

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push praveshparashar77081/user-service
          docker push praveshparashar77081/product-service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.20.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
