name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for User service
        run: npm install --prefix ./user-service

      - name: Install dependencies for Product service
        run: npm install --prefix ./product-service

      - name: Build Docker images
        run: |
          docker build -t praveshparashar77081/user-service ./user-service
          docker build -t praveshparashar77081/product-service ./product-service

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push praveshparashar77081/user-service
          docker push praveshparashar77081/product-service

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          sudo -u $USER minikube start --driver=docker

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context minikube
          kubectl config view

      - name: Validate Kubernetes configuration
        run: |
          kubectl cluster-info || { echo 'Failed to get cluster info'; exit 1; }
          kubectl get pods || { echo 'Failed to get pods'; exit 1; }
          kubectl get services || { echo 'Failed to get services'; exit 1; }

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f product-deployment.yml || { echo 'Failed to apply product-deployment.yml'; exit 1; }
          kubectl apply -f product-service.yml || { echo 'Failed to apply product-service.yml'; exit 1; }
          kubectl apply -f user-deployment.yml || { echo 'Failed to apply user-deployment.yml'; exit 1; }
          kubectl apply -f user-service.yml || { echo 'Failed to apply user-service.yml'; exit 1; }
